config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: { registrations: 'registrations' }

  resources :salons
  resources :orders
  resources :customers

  get 'sort/:id/:by' => 'salons#show', as: 'sort'
  root 'salons#index'

  namespace :admin do
    resources :salons
    resources :cars
    resources :customers
    resources :orders

    root 'admin#index'
  end
end

app/views/navbar/_nav.html.erb
<nav class="navbar navbar-dark navbar-1">
  <div class="sidebar-logo-1">
    <%= link_to 'RentCar', root_path, id: 'demoFont-1', class: 'navbar-brand-1'%>
  </div>
  <% if current_customer.present? %>
    <div class="position-body-navbar-customer">
      <%= link_to customer_path(current_customer), class: 'nav-link link-color nav-link-edit' do%>
      <div class="link">
        <% if current_customer.avatar.present? %>
          <%= image_tag current_customer.avatar.thumb.url, class: 'customer-avatar'%>
        <%else %>
          <%= image_tag 'https://cdn.pixabay.com/photo/2012/04/26/19/43/profile-42914_960_720.png',
            class: 'customer-avatar'%>
        <%end %>
        <h5 class="name-customer">
          <%= current_customer.name %>
        </h5>
      </div>
        <% end %>
    <ul class="navbar-nav mt-2 mt-lg-0" >
      <li class="nav-item link link-out">
        <%= link_to 'Long out', destroy_customer_session_path, method: 'delete', class: 'nav-link link-color' %>
      </li>
  <%else %>
    <div class="position-body-navbar">
      <li class="nav-item link">
        <%= link_to 'Sign up', new_customer_registration_path, class: 'nav-link link-color' %>
      </li>
      <li class="nav-item link">
        <%= link_to 'Log in', customer_session_path, class: 'nav-link link-color' %>
      </li>
    </div>
  <%end %>
  </ul>
  </div>
</nav>