config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: { registrations: 'registrations' }

  resources :salons
  resources :orders
  resources :customers

  get 'sort/:id/:by' => 'salons#show', as: 'sort'
  root 'salons#index'

  namespace :admin do
    resources :salons
    resources :cars
    resources :customers
    resources :orders

    root 'admin#index'
  end
end

app/models/salon.rb
class Salon < ApplicationRecord

  has_many :cars
  has_many :orders

  has_one :picture, as: :imageable, class_name: 'Image', dependent: :destroy
  accepts_nested_attributes_for :picture

  paginates_per 6
end

app/controllers/admin/salons_controller.rb
class Admin::SalonsController < Admin::AdminController
  before_action :find_salon, only: %i[ show edit update destroy]

  def index
    @salons = Salon.order(:name).page params[:page]
  end

  def show; end

  def new
    @salon = Salon.new
  end

  def create
    @salon = Salon.create(salons_params)
    if @salon.save
      redirect_to admin_salons_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @salon.update(salons_params)
      redirect_to admin_salon_path(@salon)
    else
      render :edit
    end
  end

  def destroy
    @salon.destroy
    redirect_to admin_salons_path
  end

  private

  def find_salon
    @salon = Salon.find(params[:id])
  end

  def salons_params
    params.require(:salon).permit(:name, :car_id, picture_attributes: %i[id url])
  end
end

app/controllers/salons_controller.rb
class SalonsController < ApplicationController
  def index
    @salons = Salon.order(:name).page params[:page]
  end

  def show
    @salon = Salon.find(params[:id])
    @cars = @salon.cars.order(:brand).page params[:page]
    sort_cars if params[:by]
    @order = Order.new
  end

  def sort_cars
    @cars = @salon.cars.order(order_by).order(:brand).page params[:page]
  end

  def order_by
    case params[:by]
    when 'age_desc' then 'age DESC'
    when 'age' then 'age'
    when 'engine_desc' then 'engine DESC'
    when 'engine' then 'engine'
    else ''
    end
  end
end

app/views/admin/salons/_form.html.erb
<div class="size_new">
  <main class="form-new">
    <h6 class="logo-new">New salon form</h6>
    <div class="form-group form-group-new">
      <%= form_for [:admin, @salon], class: 'md-form' do |f| %>
        <%= f.fields_for :picture, @salon.picture || @salon.build_picture do |ff| %>
          <%= ff.label :url, 'Image', class: 'label' %>
          <%= ff.file_field :url , class: 'image-salon' %>
          <small id="bodyHelp" class="form-text text-danger">
            <%= @salon.errors['picture.url'].join(', ') %>
          </small>
        <% end %>
        <div class="field">
          <%= f.label :name, 'Salon name', class: 'label' %>
          <%= f.search_field :name, required: true, autocomplete: 'name', class: 'form-control borders-new-salon',
            placeholder: 'Enter name' %>
        </div>
        <div class="butt-height">
          <%= button_tag 'Save', class: ' btn btn-primary button-salon-new' %>
        </div>
      <% end %>
    </div>
  </main>
</div>

app/views/admin/salons/_salon.html.erb
 <th scope="row"><%=salon.id %></th>
  <% if salon.picture.present? %>
    <td class="image-padding "><%= image_tag salon.picture.url.url, class: 'image_salons'%></td>
  <% else %>
    <td class="image-padding ">
      <img src="https://www.driversupport.com/wp-content/uploads/2018/04/Placeholder.gif"
           alt="image" class="image_salons">
    </td>
  <% end %>
  <td class="width-name"><%= salon.name%></td>
  <td><%=salon.created_at%></td>
  <td><%=salon.updated_at%></td>

app/views/admin/salons/edit.html.erb
<%= render 'form' %>

app/views/admin/salons/index.html.erb
<div class="index-salons">
  <main class="table-tb">
    <div class="table-logo">
      <div class="logo">
        <h4>Salons Table</h4>
      </div>
      <div class="link-new">
        <%= link_to 'New salon', new_admin_salon_path, class: 'new-salon' %>
      </div>
      <div class="paginate-salon-top">
      <%= paginate @salons %>
      </div>
      <table class="table table-bordered margin_table">
        <thead>
        <tr>
          <th scope="col">Id</th>
          <th scope="col">Image</th>
          <th scope="col">Name</th>
          <th scope="col">Created at</th>
          <th scope="col">Updated at</th>
        </tr>
        </thead>
        <tbody>
        <% @salons.each do |salon| %>
          <tr onclick="window.location.href='<%= admin_salon_path(salon) %>'; return false" class="salon-hover">
            <%= render salon %>
          </tr>
        <% end %>
        </tbody>
      </table>
      <div class="paginate-salon-bottom">
        <%= paginate @salons %>
      </div>
    </div>
  </main>
</div>

app/views/admin/salons/new.html.erb
<%= render 'form' %>

app/views/admin/salons/show.html.erb
<div class="media size-salons-show">
  <main class="show-maim">
      <div class="show-display">
        <div class="image-show">
        <% if @salon.picture.present? %>
          <%= image_tag @salon.picture.url.url, class: 'media-object image-wid-hei-show '%>
        <% else %>
          <img src="https://www.driversupport.com/wp-content/uploads/2018/04/Placeholder.gif"
               alt=" media-object image" class="image-wid-hei-show ">
        <% end %>
      </div>
      <div class="show-table">
        <table class="table table-bordered">
          <thead>
          </thead>
          <tbody>
            <tr><td>Id:</td><td><%= @salon.id %></td></tr>
            <tr><td>Name:</td><td><%= @salon.name %></td></tr>
            <tr><td>Created At:</td><td><%= @salon.created_at%></td></tr>
            <tr><td>Updated At:</td><td><%= @salon.updated_at%></td></tr>
          </tbody>
        </table>
        </div>
    <div class="link-show">
      <%= link_to 'Edit', edit_admin_salon_path(@salon), class: 'button_show button-margin' %>
      <%= link_to 'Delete', admin_salon_path, method: :delete, class: 'button_show button-margin' %>
    </div>
      </div>
  </main>
</div>