config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: { registrations: 'registrations' }

  resources :salons
  resources :orders
  resources :customers

  get 'sort/:id/:by' => 'salons#show', as: 'sort'
  root 'salons#index'

  namespace :admin do
    resources :salons
    resources :cars
    resources :customers
    resources :orders

    root 'admin#index'
  end
end

app/models/car.rb
class Car < ApplicationRecord

  extend Enumerize

  belongs_to :salon
  has_many :orders

  has_one :picture, as: :imageable, class_name: 'Image', dependent: :destroy
  accepts_nested_attributes_for :picture

  paginates_per 6

  enumerize :fuel_type, in: %i[diesel gasoline electricity gas hybrid]
  enumerize :age, in: 1990..2020
end

app/controllers/admin/cars_controller.rb
class Admin::CarsController < Admin::AdminController
  before_action :find_car, only: %i[show edit update destroy]

  def index
    @cars = Car.order(:brand).page params[:page]
  end

  def show; end

  def new
    @car = Car.new
  end

  def create
    @car = Car.create(cars_params)
    if @car.save
      redirect_to admin_cars_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @car.update(cars_params)
      redirect_to admin_car_path(@car)
    else
      render :edit
    end
  end

  def destroy
    if @car.destroy
      redirect_to admin_cars_path
    end
  end

  private

  def find_car
    @car = Car.find(params[:id])
  end

  def cars_params
    params.require(:car).permit(
      :id, :brand, :model, :color, :fuel_type, :age, :engine, :enum_status, :salon_id, picture_attributes: %i[id url]
    )
  end
end

app/views/cars/_car.html.erb
<div class="car-positions car-hover">
  <main class="main-car">
    <div class="car">
      <div>
        <% if car.picture.present? %>
          <%= image_tag car.picture.url.url, class: 'image-size-car' %>
        <% else %>
          <%= image_tag 'https://www.driversupport.com/wp-content/uploads/2018/04/Placeholder.gif',
            class: 'image-size-car' %>
        <% end %>
      </div>
      <div class="position-car-points">
        <div id="container-car-1" >
          <h3 class="car-name">
            <%= car.brand %>
            <%= car.model %>
          </h3>
          <div class="points-position">
            <i class="fas fa-tint car-points"></i> <p class="points color-points"><%= car.color %></p>
          </div>
          <div class="points-position">
            <i class="far fa-calendar-alt car-points"></i> <p class="points color-points"> <%=car.age %></p>
          </div>
          <div class="points-position">
            <i class="fas fa-cogs car-points" ></i> <p class="points color-points"> engine <%= car.engine %></p>
          </div>
          <div class="points-position">
            <i class="fas fa-gas-pump car-points"></i> <p class="points color-points"> <%= car.fuel_type %></p>
          </div>
          <div class="points-position">
            <% if car.enum_status? %>
              <i class="fas fa-unlock-alt car-points"></i><p class="points status-free">free</p>
            <% else %>
              <i class="fas fa-unlock-alt car-points"></i><p class="points status-close">close</p>
            <%end %>
          </div>
        </div>
        <div id="container-car-2" >
          <h3 class="car-price"> Price per day: 1000$</h3>
          <% if current_customer.present? %>
            <% if car.enum_status? %>
              <%= form_for @order do |f| %>
                <%= f.hidden_field :customer_name, value: current_customer.name %>
                <%= f.hidden_field :car_brand, value: car.brand %>
                <%= f.hidden_field :car_model, value: car.model %>
                <%= f.hidden_field :customer_id, value: current_customer.id %>
                <%= f.hidden_field :car_id,  value: car.id %>
                <%= f.hidden_field :salon_id, value: @salon.id %>
                <%= f.hidden_field :salon_name, value: @salon.name %>
                <div class="button-rent-position">
                  <%= button_tag 'Rent car' ,class: 'button-rent-car' %>
                </div>
              <%end %>
            <%end %>
          <%end %>
        </div>
      </div>
    </div>
  </main>
</div>

app/views/cars/_sort.html.erb
<div class="sort">
    <p class="text-center">
      Sort by Age:
      <%= link_to sort_path('age_desc') do %>
        <i class="fas fa-chevron-circle-down"></i>
      <% end %>
      <%= link_to sort_path('age') do %>
        <i class="fas fa-chevron-circle-up"></i>
      <% end %>
      by Engine:
      <%= link_to sort_path('engine_desc') do %>
        <i class="fas fa-chevron-circle-down"></i>
      <% end %>
      <%= link_to sort_path('engine') do %>
        <i class="fas fa-chevron-circle-up"></i>
      <% end %>
    </p>
</div>